# Generated by Django 5.2.1 on 2025-07-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='idea_uploads/'),
        ),
    ]
